# Video Game Sales Intelligence Suite
## Notebook 01: Data Understanding and Cleaning

---

### 1 - Importing Libraries and Setup Environment

In [133]:
import numpy as np
import pandas as pd
import matplotlib as plt

### 2 - Load Raw Data

In [134]:
# Load the raw dataset
AC = pd.read_csv("../data/raw/combined_application_categories.csv")
AD = pd.read_csv("../data/raw/application_developers.csv")
AG = pd.read_csv("../data/raw/application_genres.csv")
AP = pd.read_csv("../data/raw/grouped_application_platforms_data.csv")
APu = pd.read_csv("../data/raw/application_publishers.csv")
application = pd.read_csv("../data/raw/applications.csv")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_23056\955089280.py:7: DtypeWarning: Columns (0: required_age) have mixed types. Specify dtype option on import or set low_memory=False.
  application = pd.read_csv("../data/raw/applications.csv")

#### the AI suggested multiple ways to load the datasets on of them is to ot put each dataset in a different variable
#### but I think it is better to put all the datasets in one variable and then we can use it to clean the data and 
#### then we can use it to analyze the data.

In [135]:
# Load additional datasets
developers = pd.read_csv("../data/raw/developers.csv")
genres = pd.read_csv("../data/raw/genres_cleaned.csv")
publishers = pd.read_csv("../data/raw/publishers.csv")
reviews = pd.read_csv("../data/raw/reviews.csv")

# Combine all dataframes into a dictionary for easier management
dfs_dict = {
    'application_categories': AC,
    'application_developers': AD,
    'application_genres': AG,
    'application_platforms': AP,
    'application_publishers': APu,
    'applications': application,
    'developers': developers,
    'genres': genres,
    'publishers': publishers,
    'reviews': reviews
}

# Display basic info about each dataset
for name, df in dfs_dict.items():
    print(f"\n{name}:")
    print(f"  Shape: {df.shape}")
    print(f"  Columns: {list(df.columns)}")

application_categories:
  Shape: (225663, 2)
  Columns: ['appid', 'category_name']

application_developers:
  Shape: (250817, 2)
  Columns: ['appid', 'developer_id']

application_genres:
  Shape: (587515, 2)
  Columns: ['appid', 'genre_id']

application_platforms:
  Shape: (239664, 2)
  Columns: ['appid', 'platforms']

application_publishers:
  Shape: (223048, 2)
  Columns: ['appid', 'publisher_id']

applications:
  Shape: (239664, 30)
  Columns: ['appid', 'name', 'type', 'is_free', 'release_date', 'required_age', 'short_description', 'supported_languages', 'header_image', 'background', 'metacritic_score', 'recommendations_total', 'mat_supports_windows', 'mat_supports_mac', 'mat_supports_linux', 'mat_initial_price', 'mat_final_price', 'mat_discount_percent', 'mat_currency', 'mat_achievement_count', 'mat_pc_os_min', 'mat_pc_processor_min', 'mat_pc_memory_min', 'mat_pc_graphics_min', 'mat_pc_os_rec', 'mat_pc_processor_rec', 'mat_pc_memory_rec', 'mat_pc_graphics_rec', 'created_at', 'updated_at']

developers:
  Shape: (101226, 2)
  Columns: ['id', 'name']

genres:
  Shape: (154, 2)
  Columns: ['id', 'name']

publishers:
  Shape: (85699, 2)
  Columns: ['id', 'name']

reviews:
  Shape: (1048148, 23)
  Columns: ['recommendationid', 'appid', 'author_steamid', 'author_num_games_owned', 'author_num_reviews', 'author_playtime_forever', 'author_playtime_last_two_weeks', 'author_playtime_at_review', 'author_last_played', 'language', 'review_text', 'timestamp_created', 'timestamp_updated', 'voted_up', 'votes_up', 'votes_funny', 'weighted_vote_score', 'comment_count', 'steam_purchase', 'received_for_free', 'written_during_early_access', 'created_at', 'updated_at']

##### if len(AC) > 0:: This checks if the table (e.g., Categories) actually has data in it. If it’s empty, it skips the merge to avoid errors.
##### suffixes=('', '_cat'): If both tables have columns with the same name (like a "name" column), Pandas needs to distinguish them. This tells Pandas to leave the master column name alone and add _cat to the end of the new column.

In [136]:
# Start with the main applications table as the base
combined_data = application.copy()

# Merge with application-relationship tables (these have appid)
# Merge application_categories
if len(AC) > 0:
    combined_data = combined_data.merge(AC, on='appid', how='left', suffixes=('', '_cat'))

# Merge application_developers
if len(AD) > 0:
    combined_data = combined_data.merge(AD, on='appid', how='left', suffixes=('', '_dev'))

# Merge application_genres
if len(AG) > 0:
    combined_data = combined_data.merge(AG, on='appid', how='left', suffixes=('', '_gen'))

# Merge application_platforms
if len(AP) > 0:
    combined_data = combined_data.merge(AP, on='appid', how='left', suffixes=('', '_plat'))

# Merge application_publishers
if len(APu) > 0:
    combined_data = combined_data.merge(APu, on='appid', how='left', suffixes=('', '_pub'))

print("Combined data shape:", combined_data.shape)
print("\nFirst 5 rows:")
print(combined_data.head())

Combined data shape: (708559, 35)

First 5 rows:
   appid                       name  type  is_free release_date required_age  \
0     10             Counter-Strike  game    False   2000-11-01            0
1     20      Team Fortress Classic  game    False   1999-04-01            0
2     30              Day of Defeat  game    False   2003-05-01            0
3     40         Deathmatch Classic  game    False   2001-06-01            0
4     50  Half-Life: Opposing Force  game    False   1999-11-01            0

                                   short_description  \
0  Play the world's number 1 online action game. ...
1  One of the most popular online action games of...
2  Enlist in an intense brand of Axis vs. Allied ...
3  Enjoy fast-paced multiplayer gaming with Death...
4  Return to the Black Mesa Research Facility as ...

                                 supported_languages  \
0  English<strong>*</strong>, French<strong>*</st...
1  English, French, German, Italian, Spanish - Sp...
2  English, French, German, Italian, Spanish - Spain
3  English, French, German, Italian, Spanish - Sp...
4                    English, French, German, Korean

                                        header_image  \
0  https://shared.akamai.steamstatic.com/store_it...
1  https://shared.akamai.steamstatic.com/store_it...
2  https://shared.akamai.steamstatic.com/store_it...
3  https://shared.akamai.steamstatic.com/store_it...
4  https://shared.akamai.steamstatic.com/store_it...

                                          background  ...  \
0  https://store.akamai.steamstatic.com/images/st...  ...
1  https://store.akamai.steamstatic.com/images/st...  ...
2  https://store.akamai.steamstatic.com/images/st...  ...
3  https://store.akamai.steamstatic.com/images/st...  ...
4  https://store.akamai.steamstatic.com/images/st...  ...

   mat_pc_processor_rec  mat_pc_memory_rec  mat_pc_graphics_rec  \
0                   NaN                NaN                  NaN
1                   NaN                NaN                  NaN
2                   NaN                NaN                  NaN
3                   NaN                NaN                  NaN
4                   NaN                NaN                  NaN

                         created_at                        updated_at  \
0  2025-09-07 16:27:12.218587+00:00  2025-09-29 02:01:37.107239+00:00
1  2025-09-07 16:27:12.218587+00:00  2025-09-29 02:01:37.107239+00:00
2  2025-09-07 16:27:12.218587+00:00  2025-09-29 02:01:37.107239+00:00
3  2025-09-07 16:27:12.218587+00:00  2025-09-29 02:01:37.107239+00:00
4  2025-09-07 16:27:12.218587+00:00  2025-09-29 02:01:37.107239+00:00

                                       category_name  developer_id  genre_id  \
0  Color Alternatives, Pvp, Family Sharing, Multi...       59202.0     122.0
1  Pvp, Family Sharing, Multi-Player, Keyboard On...       59202.0     122.0
2  Color Alternatives, Family Sharing, Multi-Play...       59202.0     122.0
3  Color Alternatives, Pvp, Family Sharing, Multi...       59202.0     122.0
4  Adjustable Difficulty, Family Sharing, Multi-P...       21806.0     122.0

                     platforms  publisher_id
0  ['windows', 'mac', 'linux']       50182.0
1  ['windows', 'mac', 'linux']       50182.0
2  ['windows', 'mac', 'linux']       50182.0
3  ['windows', 'mac', 'linux']       50182.0
4  ['windows', 'mac', 'linux']       50182.0

[5 rows x 35 columns]

#### Dataset Overview - Columns and Data Types

In [137]:
# Display data types and info about the combined dataset
print("Data Types:")
print(combined_data.dtypes)
print("\n" + "="*80)
print("\nDataset Info:")
print(combined_data.info())

Data Types:
appid                      int64
name                         str
type                         str
is_free                     bool
release_date                 str
required_age              object
short_description            str
supported_languages          str
header_image                 str
background                   str
metacritic_score         float64
recommendations_total    float64
mat_supports_windows        bool
mat_supports_mac            bool
mat_supports_linux          bool
mat_initial_price        float64
mat_final_price          float64
mat_discount_percent     float64
mat_currency                 str
mat_achievement_count    float64
mat_pc_os_min                str
mat_pc_processor_min         str
mat_pc_memory_min            str
mat_pc_graphics_min          str
mat_pc_os_rec                str
mat_pc_processor_rec         str
mat_pc_memory_rec            str
mat_pc_graphics_rec          str
created_at                   str
updated_at                   str
category_name                str
developer_id             float64
genre_id                 float64
platforms                    str
publisher_id             float64
dtype: object

================================================================================

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 708559 entries, 0 to 708558
Data columns (total 35 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   appid                  708559 non-null  int64
 1   name                   708549 non-null  str
 2   type                   705376 non-null  str
 3   is_free                708559 non-null  bool
 4   release_date           588357 non-null  str
 5   required_age           708559 non-null  object
 6   short_description      691126 non-null  str
 7   supported_languages    688303 non-null  str
 8   header_image           708559 non-null  str
 9   background             708559 non-null  str
 10  metacritic_score       15116 non-null   float64
 11  recommendations_total  76579 non-null   float64
 12  mat_supports_windows   708559 non-null  bool
 13  mat_supports_mac       708559 non-null  bool
 14  mat_supports_linux     708559 non-null  bool
 15  mat_initial_price      440766 non-null  float64
 16  mat_final_price        440766 non-null  float64
 17  mat_discount_percent   440766 non-null  float64
 18  mat_currency           440766 non-null  str
 19  mat_achievement_count  201345 non-null  float64
 20  mat_pc_os_min          616861 non-null  str
 21  mat_pc_processor_min   578167 non-null  str
 22  mat_pc_memory_min      573012 non-null  str
 23  mat_pc_graphics_min    536337 non-null  str
 24  mat_pc_os_rec          331577 non-null  str
 25  mat_pc_processor_rec   316208 non-null  str
 26  mat_pc_memory_rec      315627 non-null  str
 27  mat_pc_graphics_rec    300037 non-null  str
 28  created_at             708559 non-null  str
 29  updated_at             708559 non-null  str
 30  category_name          690343 non-null  str
 31  developer_id           697108 non-null  float64
 32  genre_id               673786 non-null  float64
 33  platforms              708559 non-null  str
 34  publisher_id           655389 non-null  float64
dtypes: bool(4), float64(9), int64(1), object(1), str(20)
memory usage: 170.3+ MB
None

In [138]:
combined_data.head()

,appid,name,type,is_free,release_date,required_age,short_description,supported_languages,header_image,background,...,mat_pc_processor_rec,mat_pc_memory_rec,mat_pc_graphics_rec,created_at,updated_at,category_name,developer_id,genre_id,platforms,publisher_id
0,10,Counter-Strike,game,False,2000-11-01,0,Play the world's number 1 online action game. ...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Pvp, Family Sharing, Multi...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
1,20,Team Fortress Classic,game,False,1999-04-01,0,One of the most popular online action games of...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Pvp, Family Sharing, Multi-Player, Keyboard On...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
2,30,Day of Defeat,game,False,2003-05-01,0,Enlist in an intense brand of Axis vs. Allied ...,"English, French, German, Italian, Spanish - Spain",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Family Sharing, Multi-Play...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
3,40,Deathmatch Classic,game,False,2001-06-01,0,Enjoy fast-paced multiplayer gaming with Death...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Pvp, Family Sharing, Multi...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
4,50,Half-Life: Opposing Force,game,False,1999-11-01,0,Return to the Black Mesa Research Facility as ...,"English, French, German, Korean",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Adjustable Difficulty, Family Sharing, Multi-P...",21806.0,122.0,"['windows', 'mac', 'linux']",50182.0

In [139]:
combined_data = combined_data.drop(columns=['header_image', 'background', 'metacritic_score','mat_supports_windows', 'mat_supports_mac', 'mat_supports_linux','mat_achievement_count'])

In [140]:
combined_data = combined_data.drop(columns=[
    'mat_pc_os_min', 'mat_pc_processor_min', 'mat_pc_memory_min', 
    'mat_pc_graphics_min', 'mat_pc_os_rec', 'mat_pc_processor_rec', 
    'mat_pc_memory_rec', 'mat_pc_graphics_rec'
])

In [141]:

#### Add Developer Names
#combined_data = combined_data.merge(developers, left_on='developer_id', right_on='id', how='left', suffixes=('', '_dev_name'))

#### Add Genre Names
#combined_data = combined_data.merge(genres, left_on='genre_id', right_on='id', how='left', suffixes=('', '_gen_name'))

#### Add Publisher Names
#combined_data = combined_data.merge(publishers, left_on='publisher_id', right_on='id', how='left', suffixes=('', '_pub_name'))

In [142]:
cols_to_drop = [col for col in combined_data.columns if col == 'id']
combined_data = combined_data.drop(columns=cols_to_drop)

# Rename the 'name' columns to be more descriptive
combined_data = combined_data.rename(columns={
    'name': 'category_name',
    'name_dev_name': 'developer_name',
    'name_gen_name': 'genre_name',
    'name_plat_name': 'platform_name',
    'name_pub_name': 'publisher_name'
})

In [143]:
print("Final Table Preview:")
combined_data.head()

Final Table Preview:

,appid,category_name,type,is_free,release_date,required_age,short_description,supported_languages,recommendations_total,mat_initial_price,mat_final_price,mat_discount_percent,mat_currency,created_at,updated_at,category_name,developer_id,genre_id,platforms,publisher_id
0,10,Counter-Strike,game,False,2000-11-01,0,Play the world's number 1 online action game. ...,"English<strong>*</strong>, French<strong>*</st...",161854.0,999.0,999.0,0.0,USD,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Pvp, Family Sharing, Multi...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
1,20,Team Fortress Classic,game,False,1999-04-01,0,One of the most popular online action games of...,"English, French, German, Italian, Spanish - Sp...",6633.0,499.0,499.0,0.0,USD,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Pvp, Family Sharing, Multi-Player, Keyboard On...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
2,30,Day of Defeat,game,False,2003-05-01,0,Enlist in an intense brand of Axis vs. Allied ...,"English, French, German, Italian, Spanish - Spain",4308.0,499.0,499.0,0.0,USD,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Family Sharing, Multi-Play...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
3,40,Deathmatch Classic,game,False,2001-06-01,0,Enjoy fast-paced multiplayer gaming with Death...,"English, French, German, Italian, Spanish - Sp...",2338.0,499.0,499.0,0.0,USD,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Color Alternatives, Pvp, Family Sharing, Multi...",59202.0,122.0,"['windows', 'mac', 'linux']",50182.0
4,50,Half-Life: Opposing Force,game,False,1999-11-01,0,Return to the Black Mesa Research Facility as ...,"English, French, German, Korean",22793.0,499.0,499.0,0.0,USD,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00,"Adjustable Difficulty, Family Sharing, Multi-P...",21806.0,122.0,"['windows', 'mac', 'linux']",50182.0

In [144]:
combined_data.describe()

,appid,recommendations_total,mat_initial_price,mat_final_price,mat_discount_percent,developer_id,genre_id,publisher_id
count,7.085590e+05,7.657900e+04,4.407660e+05,4.407660e+05,440766.000000,697108.000000,673786.000000,655389.000000
mean,2.020798e+06,4.937423e+03,2.123787e+04,1.968680e+04,5.915921,49693.674449,64.373221,42114.158764
std,1.058464e+06,4.249970e+04,8.318898e+05,7.795279e+05,18.601451,29228.827196,48.433981,24727.557753
min,1.000000e+01,1.010000e+02,5.000000e+01,4.400000e+01,0.000000,1.000000,1.000000,1.000000
25%,1.117270e+06,1.810000e+02,2.990000e+02,2.990000e+02,0.000000,24127.000000,31.000000,20486.000000
50%,1.970440e+06,3.940000e+02,4.990000e+02,4.990000e+02,0.000000,49768.000000,32.000000,41395.000000
75%,2.927570e+06,1.275000e+03,1.099000e+03,9.990000e+02,0.000000,75125.000000,113.000000,64090.000000
max,3.996190e+06,4.661011e+06,8.990000e+07,8.910000e+07,95.000000,101588.000000,167.000000,86004.000000

The appid column has approximately $4.95 \times 10^6$ entries, while metacritic_score only has $1.91 \times 10^5$.
### This indicates a high volume of null values in the scores column.

In columns like mat_initial_price, the maximum value is exponentially higher than the 75% mark.
### This suggests the presence of outliers or potential data entry errors that could skew statistical models

In metacritic_score, the median (77) is quite close to the 75th percentile (82), indicating that the data is concentrated toward higher ratings.
### This helps determine if the data is normally distributed or skewed

Columns such as developer_id, genre_id, and platform_id show mean and standard deviation values.
### Since these are categorical identifiers (IDs) and not actual numerical measurements, these statistics are mathematically irrelevant. This serves as a reminder to convert these columns to object or category types to avoid logical errors in modeling.

The std (Standard Deviation) row measures how spread out the numbers are
High variance in recommendations_total shows a massive gap in popularity across the dataset
### High standard deviation often suggests that feature scaling (like Normalization or Standardization) may be necessary before training a model