# Steam Game Intelligence Suite
## Notebook 01: Data Understanding and Cleaning

---

### 1 - Setup Environment and Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
from pathlib import Path
from IPython.display import display

### 2 - Load Raw Data

In [ ]:
# Create Path object
raw_dir = Path("data/raw")

# Resolve the raw folder from the notebook working directory or any parent folder.
candidates = [raw_dir] + [Path(p) / "data" / "raw" for p in Path.cwd().resolve().parents]
raw_dir = next((p for p in candidates if p.exists()), None)
if raw_dir is None:
    raise FileNotFoundError(
        "Could not locate the raw data folder. Tried: " + ", ".join(str(p) for p in candidates)
    )

# List of raw files
csv_files = [
    "applications.csv",
    "reviews.csv",
    "genres.csv",
    "categories.csv",
    "developers.csv",
    "platforms.csv",
    "publishers.csv",
    "application_genres.csv",
    "application_categories.csv",
    "application_developers.csv",
    "application_platforms.csv",
    "application_publishers.csv",
]

# Load all files
dfs = {name.replace(".csv", ""): pd.read_csv(raw_dir / name, low_memory=False) for name in csv_files}

# Schema descriptions
schema = {
    "applications": {
        "appid": "Unique app identifier",
        "name": "Game/application title",
        "type": "Application type (e.g. game/software)",
        "is_free": "Whether the app is free",
        "release_date": "Release date",
        "required_age": "Minimum age requirement",
        "short_description": "Summary description text",
        "supported_languages": "Supported languages",
        "header_image": "Header image URL",
        "background": "Background image URL",
        "metacritic_score": "Metacritic score",
        "recommendations_total": "Total recommendations",
        "mat_supports_windows": "Supports Windows",
        "mat_supports_mac": "Supports macOS",
        "mat_supports_linux": "Supports Linux",
        "mat_initial_price": "Initial price",
        "mat_final_price": "Final price",
        "mat_discount_percent": "Discount percentage",
        "mat_currency": "Currency code",
        "mat_achievement_count": "Achievement count",
        "mat_pc_os_min": "Minimum PC OS requirement",
        "mat_pc_processor_min": "Minimum CPU requirement",
        "mat_pc_memory_min": "Minimum RAM requirement",
        "mat_pc_graphics_min": "Minimum GPU requirement",
        "mat_pc_os_rec": "Recommended PC OS",
        "mat_pc_processor_rec": "Recommended CPU",
        "mat_pc_memory_rec": "Recommended RAM",
        "mat_pc_graphics_rec": "Recommended GPU",
        "created_at": "Record creation timestamp",
        "updated_at": "Record update timestamp",
    },
    "reviews": {
        "recommendationid": "Unique review identifier",
        "appid": "App identifier for this review",
        "author_steamid": "Steam ID of review author",
        "author_num_games_owned": "Number of games owned by author",
        "author_num_reviews": "Number of reviews written by author",
        "author_playtime_forever": "Total playtime in minutes",
        "author_playtime_last_two_weeks": "Playtime in last 2 weeks",
        "author_playtime_at_review": "Playtime at time of review",
        "author_last_played": "Last played timestamp",
        "language": "Review language",
        "review_text": "Review text",
        "timestamp_created": "Review creation timestamp",
        "timestamp_updated": "Review update timestamp",
        "voted_up": "Whether the review is positive",
        "votes_up": "Upvotes received",
        "votes_funny": "Funny votes received",
        "weighted_vote_score": "Weighted review score",
        "comment_count": "Number of comments on review",
        "steam_purchase": "Purchased on Steam flag",
        "received_for_free": "Received free copy flag",
        "written_during_early_access": "Written during early access flag",
        "created_at": "Record ingestion creation timestamp",
        "updated_at": "Record ingestion update timestamp",
    },
    "genres": {"id": "Genre identifier", "name": "Genre name"},
    "categories": {"id": "Category identifier", "name": "Category name"},
    "developers": {"id": "Developer identifier", "name": "Developer name"},
    "publishers": {"id": "Publisher identifier", "name": "Publisher name"},
    "platforms": {"id": "Platform identifier", "name": "Platform name"},
    "application_genres": {
        "appid": "App identifier",
        "genre_id": "Genre identifier",
    },
    "application_categories": {
        "appid": "App identifier",
        "category_id": "Category identifier",
    },
    "application_developers": {
        "appid": "App identifier",
        "developer_id": "Developer identifier",
    },
    "application_publishers": {
        "appid": "App identifier",
        "publisher_id": "Publisher identifier",
    },
    "application_platforms": {
        "appid": "App identifier",
        "platform_id": "Platform identifier",
    },
}

# Print summary and display schema as tables
for name, df in dfs.items():
    print(f"\n=== {name}.csv ===")
    print("Shape:", df.shape)
    schema_df = pd.DataFrame(
        [
            {
                "column": col,
                "purpose": schema.get(name, {}).get(col, "No description available"),
            }
            for col in df.columns
        ]
    )
    display(schema_df)

=== applications.csv ===
Shape: (239664, 30)

                   column                                purpose
0                   appid                  Unique app identifier
1                    name                 Game/application title
2                    type  Application type (e.g. game/software)
3                 is_free                Whether the app is free
4            release_date                           Release date
5            required_age                Minimum age requirement
6       short_description               Summary description text
7     supported_languages                    Supported languages
8            header_image                       Header image URL
9              background                   Background image URL
10       metacritic_score                       Metacritic score
11  recommendations_total                  Total recommendations
12   mat_supports_windows                       Supports Windows
13       mat_supports_mac                         Supports macOS
14     mat_supports_linux                         Supports Linux
15      mat_initial_price                          Initial price
16        mat_final_price                            Final price
17   mat_discount_percent                    Discount percentage
18           mat_currency                          Currency code
19  mat_achievement_count                      Achievement count
20          mat_pc_os_min              Minimum PC OS requirement
21   mat_pc_processor_min                Minimum CPU requirement
22      mat_pc_memory_min                Minimum RAM requirement
23    mat_pc_graphics_min                Minimum GPU requirement
24          mat_pc_os_rec                      Recommended PC OS
25   mat_pc_processor_rec                        Recommended CPU
26      mat_pc_memory_rec                        Recommended RAM
27    mat_pc_graphics_rec                        Recommended GPU
28             created_at              Record creation timestamp
29             updated_at                Record update timestamp

=== reviews.csv ===
Shape: (1048148, 23)

                            column                              purpose
0                 recommendationid             Unique review identifier
1                            appid       App identifier for this review
2                   author_steamid            Steam ID of review author
3           author_num_games_owned      Number of games owned by author
4               author_num_reviews  Number of reviews written by author
5          author_playtime_forever            Total playtime in minutes
6   author_playtime_last_two_weeks             Playtime in last 2 weeks
7        author_playtime_at_review           Playtime at time of review
8               author_last_played                Last played timestamp
9                         language                      Review language
10                     review_text                          Review text
11               timestamp_created            Review creation timestamp
12               timestamp_updated              Review update timestamp
13                        voted_up       Whether the review is positive
14                        votes_up                     Upvotes received
15                     votes_funny                 Funny votes received
16             weighted_vote_score                Weighted review score
17                   comment_count         Number of comments on review
18                  steam_purchase              Purchased on Steam flag
19               received_for_free              Received free copy flag
20     written_during_early_access     Written during early access flag
21                      created_at  Record ingestion creation timestamp
22                      updated_at    Record ingestion update timestamp

=== genres.csv ===
Shape: (154, 2)

  column           purpose
0     id  Genre identifier
1   name        Genre name

=== categories.csv ===
Shape: (462, 2)

  column              purpose
0     id  Category identifier
1   name        Category name

=== developers.csv ===
Shape: (101226, 2)

  column               purpose
0     id  Developer identifier
1   name        Developer name

=== platforms.csv ===
Shape: (3, 2)

  column              purpose
0     id  Platform identifier
1   name        Platform name

=== publishers.csv ===
Shape: (85699, 2)

  column               purpose
0     id  Publisher identifier
1   name        Publisher name

=== application_genres.csv ===
Shape: (587515, 2)

     column           purpose
0     appid    App identifier
1  genre_id  Genre identifier

=== application_categories.csv ===
Shape: (1077156, 2)

        column              purpose
0        appid       App identifier
1  category_id  Category identifier

=== application_developers.csv ===
Shape: (250817, 2)

         column               purpose
0         appid        App identifier
1  developer_id  Developer identifier

=== application_platforms.csv ===
Shape: (334671, 2)

        column              purpose
0        appid       App identifier
1  platform_id  Platform identifier

=== application_publishers.csv ===
Shape: (223048, 2)

         column               purpose
0         appid        App identifier
1  publisher_id  Publisher identifier